### ISSUE TITLE
File -> Save input string reverses typing

### ISSUE THREAD

**Issue by glawler** [STEELISI/DEW-issues#1]
When going to File -> Save and typing a name to save under, the cursor jumps back to the start of the line causing the text typed to reverse. 
![reversetext](https://user-images.githubusercontent.com/1774652/95476982-df68f580-0955-11eb-8b2b-8294359fd497.gif)

**Comment by ramkumar-kr** [comment]
Hi,
I have fixed this bug and deployed it to the server.
