### ISSUE TITLE
Account creation 

### ISSUE THREAD

**Issue by jelenamirkovic** [STEELISI/DEW-issues#14]
Instead of "type of institution" just put "institution"
Also if user is not logged into Gmail they are prompted to log into "isi.edu" (you can see this if you try from incognito window)
They should be prompted to log into Gmail

**Comment by ramkumar-kr** [comment]
Hello professor,

Regarding the "isi.edu" part, I don't think it is possible today to customize since Google shows the top level domain of the website we are trying to sign in (which is isi.edu for us).

**Comment by ramkumar-kr** [comment]
The type of institution fix has been deployed. Closing since the log in screen view is controlled by google.
