### ISSUE TITLE
Make sure all conditions (files and vars) in Bash have unique names

### ISSUE THREAD

**Issue by jelenamirkovic** [STEELISI/DEW-issues#19]
instead of res1 and lastCmdResult

**Comment by darshanhs09** [comment]
I have fixed this. But If the variable is unused, I will be using the same name.


Example:



#!/usr/bin/bash
if [ -z "$1" ]
then
	echo "Experiment Name must be passed as argument 1"
	exit 0
fi
if [ -z "$2" ]
then
	echo "Project Name must be passed as argument 2"
	exit 0
fi
exp=$1
proj=$2
ssh server.$exp.$proj.isi.deterlab.net 'rm ~/sdone;sudo apt-get install iperf -y;echo $? > ~/sdone' &
ssh client.$exp.$proj.isi.deterlab.net 'rm ~/cdone;sudo apt-get install iperf -y;echo $? > ~/cdone' &
while [ ! -e ~/sdone ] ; do
	sleep 1
done
lastCmdResult1=`ssh server.$exp.$proj.isi.deterlab.net 'cat ~/sdone'`
sdone=""
if [ $lastCmdResult1 -eq 0 ]
then
	sdone=`echo $?`
fi
while [ ! -e ~/cdone ] ; do
	sleep 1
done
lastCmdResult2=`ssh client.$exp.$proj.isi.deterlab.net 'cat ~/cdone'`
cdone=""
if [ $lastCmdResult2 -eq 0 ]
then
	cdone=`echo $?`
fi
if [ -z "$sdone" ] || [ -z "$cdone" ]
then
	 echo "Events:sdone cdone  is not set"
else
	ssh server.$exp.$proj.isi.deterlab.net 'rm ~/res1;iperf -s;echo $? > ~/res1' &
	while [ ! -e ~/res1 ] ; do
		sleep 1
	done
	lastCmdResult=`ssh server.$exp.$proj.isi.deterlab.net 'cat ~/res1'`
fi
if [ -z "$sdone" ] || [ -z "$cdone" ]
then
	 echo "Events:sdone cdone  is not set"
else
	ssh client.$exp.$proj.isi.deterlab.net 'rm ~/res2;iperf -c server;echo $? > ~/res2' &
	while [ ! -e ~/res2 ] ; do
		sleep 1
	done
	lastCmdResult=`ssh client.$exp.$proj.isi.deterlab.net 'cat ~/res2'`
fi
