### ISSUE TITLE
Just a suggestion: Autosave / Logout notification

### ISSUE THREAD

**Issue by rajattan** [STEELISI/DEW-issues#3]
If a user is working on a Dew experiment and something else comes up. And if the user comes back to the previously opened Dew experiment after sometime.

The current Web Page still allows the user to edit the logged out page. And pops up the log out notification when the user clicks  on File->Save.
This leads the entered information to be unsaved and the effort may go waste.

Will it be better to autosave changes before logout and enable a pop-up notification on auto-logout? 

Current example, I did some work on my Dew experiment and then switched tabs of the browser to do some higher priority work and then when I came back. It still allowed me to edit the Web page. But when I clicked on File->Save, it popped up that I am already logged out.
<img width="1138" alt="Screen Shot 2020-10-08 at 4 38 43 PM" src="https://user-images.githubusercontent.com/22352647/95525007-c1b48400-0987-11eb-901b-82e991cf9f77.png">

**Comment by ramkumar-kr** [comment]
Autosave feature has now been added to the website

**Comment by rajattan** [comment]
Thanks @ramkumar-kr !!
