### ISSUE TITLE
invalid bash for iperf example without labels

### ISSUE THREAD

**Issue by jelenamirkovic** [STEELISI/DEW-issues#32]
![image](https://user-images.githubusercontent.com/773033/97128704-42021580-16fa-11eb-9ae0-8b1992be7173.png)

produces invalid bash below

################################################################################
#	[Scenario]                                                                 #
#	client setupClient emit clientRunsetupClientSig                            #
#	server setupServer emit serverRunsetupServerSig                            #
#	when serverRunsetupServerSig server runServer emit serverRunrunServerSig   #
#	when clientRunsetupClientSig, serverRunrunServerSig client runClient       #
#	[Bindings]                                                                 #
#	setupClient = sudo apt-get install -y iperf                                #
#	setupServer = sudo apt-get install -y iperf                                #
#	runServer = iperf -s                                                       #
#	runClient = iperf -c server                                                #
#	serverRunsetupServerSig = psuccess(setupServer)                            #
#	clientRunsetupClientSig = psuccess(setupClient)                            #
#	serverRunrunServerSig = pexists(runServer)                                 #
################################################################################
#!/usr/bin/bash
if [ -z "$1" ]
then
	echo "Usage: ./bashFile.sh experimentName projectName [arguments]"
	exit 0
fi
if [ -z "$2" ]
then
	echo "Usage: ./bashFile.sh experimentName projectName [arguments]"
	exit 0
fi
exp=$1
proj=$2
rm -f ~/clientRunsetupClientSig
ssh client.$exp.$proj.isi.deterlab.net 'sudo apt-get install -y iperf;echo $? > ~/clientRunsetupClientSig' &
rm -f ~/serverRunsetupServerSig
ssh server.$exp.$proj.isi.deterlab.net 'sudo apt-get install -y iperf;echo $? > ~/serverRunsetupServerSig' &
	rm -f ~/serverRunrunServerSig
	ssh server.$exp.$proj.isi.deterlab.net 'iperf -s;echo $? > ~/serverRunrunServerSig' &
	while [ ! -e ~/serverRunrunServerSig ] ; do
		sleep 1
	done
	lastCmdResult3=`ssh server.$exp.$proj.isi.deterlab.net 'cat ~/serverRunrunServerSig'`
fi
while [ ! -e ~/clientRunsetupClientSig ] ; do
	sleep 1
done
lastCmdResult1=`ssh client.$exp.$proj.isi.deterlab.net 'cat ~/clientRunsetupClientSig'`
clientRunsetupClientSig=""
if [ $lastCmdResult1 -eq 0 ]
then
	clientRunsetupClientSig=`echo $?`
fi
serverRunrunServerSig=""
if [ $lastCmdResult3 -eq 0 ]
then
	pexists(runServer) 
	serverRunrunServerSig=`echo $?`
fi
if [ -z "$clientRunsetupClientSig" ] || [ -z "$serverRunrunServerSig" ]
then
	 echo "Events:clientRunsetupClientSig serverRunrunServerSig  is not set"
else
	rm -f ~/res1
	ssh client.$exp.$proj.isi.deterlab.net 'iperf -c server;echo $? > ~/res1' &
	while [ ! -e ~/res1 ] ; do
		sleep 1
	done
	lastCmdResult=`ssh client.$exp.$proj.isi.deterlab.net 'cat ~/res1'`
fi

**Comment by darshanhs09** [comment]
Now, It is working fine. Bash File is generated correctly.

BASH FILE:

################################################################################
#	[Scenario]                                                                 #
#	client setupClient emit clientRunsetupClientSig                            #
#	server setupServer emit serverRunsetupServerSig                            #
#	when serverRunsetupServerSig server runServer emit serverRunrunServerSig   #
#	when clientRunsetupClientSig, serverRunrunServerSig client runClient       #
#	[Bindings]                                                                 #
#	setupClient = sudo apt-get install -y iperf                                #
#	clientRunsetupClientSig = psuccess(setupClient)                            #
#	setupServer = sudo apt-get install -y iperf                                #
#	serverRunsetupServerSig = psuccess(setupServer)                            #
#	runServer = iperf -s                                                       #
#	serverRunrunServerSig = pexists(runServer)                                 #
#	runClient = iperf -c server                                                #
################################################################################
#!/usr/bin/bash
if [ -z "$1" ]
then
	echo "Usage: ./bashFile.sh experimentName projectName [arguments]"
	exit 0
fi
if [ -z "$2" ]
then
	echo "Usage: ./bashFile.sh experimentName projectName [arguments]"
	exit 0
fi
exp=$1
proj=$2
rm -f ~/clientRunsetupClientSig
ssh client.$exp.$proj.isi.deterlab.net 'sudo apt-get install -y iperf;echo $? > ~/clientRunsetupClientSig' &
rm -f ~/serverRunsetupServerSig
ssh server.$exp.$proj.isi.deterlab.net 'sudo apt-get install -y iperf;echo $? > ~/serverRunsetupServerSig' &
while [ ! -e ~/serverRunsetupServerSig ] ; do
	sleep 1
done
lastCmdResult2=`ssh server.$exp.$proj.isi.deterlab.net 'cat ~/serverRunsetupServerSig'`
serverRunsetupServerSig=""
if [ $lastCmdResult2 -eq 0 ]
then
	serverRunsetupServerSig=`echo $?`
fi
if [ -z "$serverRunsetupServerSig" ]
then
	 echo "Events:serverRunsetupServerSig  is not set"
else
	rm -f ~/serverRunrunServerSig
	ssh server.$exp.$proj.isi.deterlab.net 'iperf -s;echo $? > ~/serverRunrunServerSig' &
	while [ ! -e ~/serverRunrunServerSig ] ; do
		sleep 1
	done
	lastCmdResult3=`ssh server.$exp.$proj.isi.deterlab.net 'cat ~/serverRunrunServerSig'`
fi
while [ ! -e ~/clientRunsetupClientSig ] ; do
	sleep 1
done
lastCmdResult1=`ssh client.$exp.$proj.isi.deterlab.net 'cat ~/clientRunsetupClientSig'`
clientRunsetupClientSig=""
if [ $lastCmdResult1 -eq 0 ]
then
	clientRunsetupClientSig=`echo $?`
fi
serverRunrunServerSig=""
if [ $lastCmdResult3 -eq 0 ]
then
	serverRunrunServerSig=`ssh server0.$exp.$proj.isi.deterlab.net 'pidof iperf'`
	while [ ! -e ~/serverRunrunServerSig ] ; do
		sleep 1
		serverRunrunServerSig=`ssh server0.$exp.$proj.isi.deterlab.net 'pidof iperf'`
	done
fi
if [ -z "$clientRunsetupClientSig" ] || [ -z "$serverRunrunServerSig" ]
then
	 echo "Events:clientRunsetupClientSig serverRunrunServerSig  is not set"
else
	rm -f ~/res1
	ssh client.$exp.$proj.isi.deterlab.net 'iperf -c server;echo $? > ~/res1' &
	while [ ! -e ~/res1 ] ; do
		sleep 1
	done
	lastCmdResult=`ssh client.$exp.$proj.isi.deterlab.net 'cat ~/res1'`
fi
